name: terraform 
on:
    push:
        branches:
            - main

jobs:
    terraform:
        environment: 'AWS'
        name: terraform-worklod 
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v2

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
                    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: "1.1.7"
            - name: Initialize Terraform
              run: terraform init

            - name: Validate Terraform
              run: terraform validate

            - name: Terraform Apply
              run: terraform apply -auto-approve tfplan



